matchBlocks=andesite black_terracotta cyan_terracotta gray_terracotta coarse_dirt cobblestone cracked_stone_bricks dirt mossy_cobblestone mossy_stone_bricks stone stone_bricks obsidian
method=fixed
biomes=badlands ocean riven birch_forest windswept_hills
tiles=<default>
connect=block