matchBlocks=soul_sand gray_terracotta nether_bricks cobblestone gravel stone_bricks light_gray_terracotta cracked_stone_bricks terracotta granite netherrack
method=fixed
biomes=nether_wastes swamp
tiles=<default>
connect=block